### ISSUE TITLE
Problem with NPM link and Angular 4

### ISSUE THREAD

**Issue by Amunds** [dolanmiu/ng-color#10]
I get the following error message when I try to run the module in Angular 4 using NPM link: `Unexpected value 'NgColorModule' imported by the module 'AppModule'. Please add a @NgModule annotation.`

Steps to reproduce:
Create a new Angular 4 application.
Git clone the ng-color repo
Run `gulp watch` in the ng-color repo
cd ./dist and npm link
Go to Angular 4 application and run npm link ng-color

**Comment by dolanmiu** [comment]
This is odd, I am experiencing this as well

**Comment by dolanmiu** [comment]
I have made a fix on `3.0.8`

Tested this on my machine and it works

Re-open if you are still experiencing
