### ISSUE TITLE
Initializers are not allowed in ambient contexts.

### ISSUE THREAD

**Issue by osaruagbonaye** [dolanmiu/ng-color#11]
Typescript Error
Initializers are not allowed in ambient contexts.
...m/node_modules/ng-color/saturation-lightness-box/saturation-lightness-image.d.ts

  | export declare const IMAGE = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOYAAACCCAYAAABSD7T3AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4AIWDwksPWR6lgAAIABJREFUeNrtnVuT47gRrAHN+P//Or/61Y5wONZ7mZ1u3XAeLMjJZGZVgdKsfc5xR3S0RIIUW+CHzCpc2McYo7XGv3ex7UiZd57rjyzzv+v+33X/R/+3r/f7vR386Y+TvKNcf/wdhTLPcv9qU2wZd74uth0t1821jkIZLPcsI/6nWa4XvutquU0Z85mnx80S/ZzgpnLnOtHNt7/ofx1TKXcSNzN/7qbMQ3ju7rNQmMYYd/4s2j9aa+P+gGa...

**Comment by dolanmiu** [comment]
How did you get this error?

Could you explain your steps

**Comment by dolanmiu** [comment]
I have made `3.0.8` which should resolve this issue

I can not reproduce this issue, I have tried `npm install`, and `npm link`, and they both work fine, so I am closing. Re-open if you still have the problem
