### ISSUE TITLE
Angular5 -prod -aot not working 

### ISSUE THREAD

**Issue by BraneMKD** [dolanmiu/ng-color#12]
Hi,

currently im using your module and trying to build with -prod and -aot flag. Im getting errors connected with this module. Is there any chance this to be fixed soon ?

Errors:
> Uncaught TypeError: e is not a constructor

Warning: (a lot of warning of this type)
> /node_modules/ng-color/ng-color.ngfactory.js
> 107:319-324 "export 'ɵj' (imported as 'i1') was not found in 'ng-color'

**Comment by dolanmiu** [comment]
This works fine in Angular 4?

Will fix soon

**Comment by dolanmiu** [comment]
Created a pull request which re-scaffolds this project according to angular spec using ng-packagr

**Comment by dolanmiu** [comment]
Fixed in `4.1.0`

Just tried it in a CLI project for sanity checking, all works :)

**Comment by BraneMKD** [comment]
Ty, just tested and its working :)
