### ISSUE TITLE
Setting color value

### ISSUE THREAD

**Issue by michel-dirix** [dolanmiu/ng-color#15]
Hi.
It seems I can't set the value of the color composant. Can you add this ? :)
I would like to set this value through an input which contains an hex color
Thanks

**Comment by dolanmiu** [comment]
you can with "startHex":

https://stackblitz.com/edit/angular-antayn?file=src%2Fapp%2Fapp.component.html

**Comment by michel-dirix** [comment]
My component is already loaded. I want to change the color dynamically. It
doesn't work when I change the startHex after.

**Comment by dolanmiu** [comment]
Done now. It is now all controlled via ngModel two way:

https://stackblitz.com/edit/ng-color-demo

Version 4.1.1

It is documented on the README

**Comment by michel-dirix** [comment]
Perfect ! Thanks !
