### ISSUE TITLE
Cannot Use Template

### ISSUE THREAD

**Issue by nla-brandonjames** [dolanmiu/ng-color#3]
I receive this error on runtime when starting my application:
`Unhandled Promise rejection: Template parse errors:
'ng-color' is not a known element:`

When compiling my application, I receive this error:
`ERROR in NgColorModule is not an NgModule`

I'm using Angular 4.0.1, and I've followed your instructions for including this module as an import.

**Comment by dolanmiu** [comment]
So sorry,

I have updated the library but did not update the README! 

It is now:

ng-color-basic
ng-colour-basic-preview

This is because later, I want this library to have other colour picker styles such as ng-color-circle etc.

Apologies!

**Comment by nla-brandonjames** [comment]
I think I will consider contributing to this library as well. There are some visual modifications I wish to make as well as features (like switching the text input from hex, rgb, etc.).

**Comment by dolanmiu** [comment]
that would be great if you could 😄

**Comment by nla-brandonjames** [comment]
I can't get TypeScript hinting when writing it in the app module either. Not sure why that is.

**Comment by dolanmiu** [comment]
hmmm, its probably because of:

```
vscode-tslint: 'Unsupported TypeScript version: 2.2.1' while validating
```

i use visual studio code, this is the error i get

**Comment by nla-brandonjames** [comment]
I see. I went to this library because I was having some issues with this color picker I tried first - http://alberplz.github.io/angular2-color-picker/examples/index.html. I like the way this developer's UI looks but he messed up by doing absolute positioning for the element so it was hard for it to play nicely. It has all the features I could want.

**Comment by nla-brandonjames** [comment]
Is it possible to make this directive - `saturation-lightness-preview` not use 100% height?

**Comment by dolanmiu** [comment]
I have updated the tslint, codelyzer, and typescript dev dependencies, which means tslint now runs

do a pull and do:

```
npm run lint
```

it throws a lot of errors, got to fix it up 😂

**Comment by dolanmiu** [comment]
and yes, I had a look at `angular2-color-picker` and frankly got fed up cos it didn't do what I wanted. And the code was pretty hideous to modify, so I decided to write a better, more flexible library.

**Comment by dolanmiu** [comment]
> Is it possible to make this directive - saturation-lightness-preview not use 100% height?

why not 100%? its meant to be a standalone component which can be used by other components. don't change the saturation-lightness-preview, `ng-color-basic`, and `ng-color-basic-preview` depend on it

**Comment by nla-brandonjames** [comment]
Do you want to move this conversation to gitter? Glad you're willing to work with me.

**Comment by dolanmiu** [comment]
how I would like this library to work is that `ng-color-basic`, and `ng-color-basic-preview` components, and in future, other components are made up of other tiny little functioning components 😄

**Comment by dolanmiu** [comment]
> Do you want to move this conversation to gitter? Glad you're willing to work with me.

yes, a gitter would be nice

**Comment by nla-brandonjames** [comment]
I'll open a new issue for the reason I am seeking to change the height of `saturation-lightness-preview`.

**Comment by dolanmiu** [comment]
ok, create a pull request to fix this

**Comment by dolanmiu** [comment]
> > Do you want to move this conversation to gitter? Glad you're willing to work with me.

> yes, a gitter would be nice

it seems like gitter is down, I cannot load it

**Comment by nla-brandonjames** [comment]
I can bring it up, it may be a problem on your side.

**Comment by dolanmiu** [comment]
ok, got gitter working
