### ISSUE TITLE
saturation-lightness-preview causes overflow of the hue slider

### ISSUE THREAD

**Issue by nla-brandonjames** [dolanmiu/ng-color#4]
See attached screenshot.
![screen shot 2017-04-17 at 10 58 35 am](https://cloud.githubusercontent.com/assets/25821918/25092750/091bd54c-235d-11e7-8617-13c41f370254.png)

The hue slider overflows off of this modal window.

**Comment by dolanmiu** [comment]
which modal is this? bootstrap?

**Comment by nla-brandonjames** [comment]
Yes. ngx-bootstrap modal.

**Comment by dolanmiu** [comment]
are you fixing this right now?

If so,

I would like to restructure this project such under `src/`, each color picker type will be in its own respective folder, which I think would make more sense

What do you think?

**Comment by nla-brandonjames** [comment]
Yeah. It sounds fine to me. One thing that may be nice to have in the future is "swatches" like graphics editor software. That could be included and structured in that way.

**Comment by dolanmiu** [comment]
yes, stuff like swatches can be added in `src/common`, so other color picker types within the lib can utilise them

**Comment by dolanmiu** [comment]
Closing because the preview color picker is deprecated
