### ISSUE TITLE
Add Angular 4 support

### ISSUE THREAD

**Issue by LeonDvlpmnt** [dolanmiu/ng-color#7]
Currently this package isn't working with Angular 4 at all.

**Comment by dolanmiu** [comment]
But this Plunkr is using Angular 4 though 😖:

http://plnkr.co/edit/N2VKBCrNNIwInwI8PVOu?p=preview

**Comment by LeonDvlpmnt** [comment]
Seems to be working in the plunkr indeed but couldn't get it working within my Angular CLI project. I'll try to take a deeper look into it. Do you want to continue support for Angular 2 or is it ok to make it work for Angular 4 or higher only?

**Comment by dolanmiu** [comment]
I believe I read somewhere that Angular 4 is backwards compatible with Angular 2.

So the answer to your question is, yes, it is ok for it to be made compatible for Angular 4

**Comment by dolanmiu** [comment]
I have re-scaffolded the entire component, and now I am confirm it works for Angular 4 (as I am using it right now in my angular/cli project!

Please re-open if it still doesnt work

Thanks

**Comment by LeonDvlpmnt** [comment]
Cheers, working fine now!

Edit: doesn't seem to be working for production/aot builds.
