### ISSUE TITLE
Plunkr sample is not working

### ISSUE THREAD

**Issue by alienriquebm** [dolanmiu/ng-color#8]
When i open the sample not works:

![image](https://cloud.githubusercontent.com/assets/5152002/25442844/22613cc2-2a74-11e7-8492-8a999fdd50e3.png)

**Comment by dolanmiu** [comment]
Yes, I am aware of this issue, it's because when migrating to Angular 2 to Angular 4, it breaks the Plunkr, will fix as soon as possible

The library still works though!

**Comment by alienriquebm** [comment]
Thanks for your time @dolanmiu , this works for Angular 4 + SystemJS?

**Comment by alienriquebm** [comment]
It gives me this error:

![image](https://cloud.githubusercontent.com/assets/5152002/25445819/70896d30-2a7d-11e7-8234-89424489fb1c.png)

**Comment by dolanmiu** [comment]
I am not sure about SystemJS, I will fix this Plunkr tonight (which uses SystemJS I believe)

But, it works on @angular/cli, as that is the one I use on my projects, and my company's projects.

**Comment by alienriquebm** [comment]
If you can help me i will appreciate so much @dolanmiu

**Comment by dolanmiu** [comment]
I have opened http://plnkr.co/edit/N2VKBCrNNIwInwI8PVOu?p=preview

and it works fine for me

Perhaps do a hard refresh?

Edit: http://plnkr.co/edit/Fd4czYfUso77G28USZtg?p=preview

try this. Fixed :) 😄

**Comment by alienriquebm** [comment]
Well... i open it with two browsers (Chrome and Firefox) and the result are the same my friend.

**Comment by dolanmiu** [comment]
try the new link I posted. It works on my computer, and my friends computer too:

http://plnkr.co/edit/Fd4czYfUso77G28USZtg?p=preview

**Comment by alienriquebm** [comment]
Yes... the result with this link http://plnkr.co/edit/N2VKBCrNNIwInwI8PVOu?p=preview:

![image](https://cloud.githubusercontent.com/assets/5152002/25446837/d27aea48-2a80-11e7-8bad-596b26d53e68.png)

**Comment by dolanmiu** [comment]
Use this link:

http://plnkr.co/edit/Fd4czYfUso77G28USZtg?p=preview

**Comment by alienriquebm** [comment]
Well... this link now works. But on my project not :( using the same config on your plunker

**Comment by dolanmiu** [comment]
What is your config? Can you send it here?

**Comment by dolanmiu** [comment]
This is fixed, so I'm closing:

http://plnkr.co/edit/Fd4czYfUso77G28USZtg?p=preview

**Comment by alienriquebm** [comment]
Thanks @dolanmiu excellent work
